import { Component } from '@angular/core';
import { assignmentDTO} from '../assignments/interfaces/assignmentDTO'

@Component({
  selector: 'app-assignments',
  templateUrl: './assignments.component.html',
  styleUrl: './assignments.component.scss'
})
export class AssignmentsComponent {

  assignments: assignmentDTO[] = [
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
    {
      id: "11111",
      name: "Crear CRUD  de Assignments",
      description: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Earum vero sit est iure! Maiores eligendi perspiciatis eveniet nihil hic quasi quis, ipsum nostrum mollitia animi error et, vero cupiditate sapiente?",
      startDate: "2020-02-01",
      endDate: "2021-02-01",
      statusId: "11111",
      statusName: "Finalizada",
      profileId: "11111",
    },
  ]
}
